# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "gpsntp"
BBFILE_PATTERN_gpsntp = "^${LAYERDIR}/"
BBFILE_PRIORITY_gpsntp = "8"

LAYERDEPENDS_gpsntp = "core openembedded-layer meta-python networking-layer"
LAYERSERIES_COMPAT_gpsntp = "dunfell"
